"""Hatchling build hook: bake precise git provenance into ``_version.py``.

Runs on every build (``uv build`` / ``uv sync`` / ``uv add <path|git>`` / ``pip install``)
with **no third-party dependency** -- pure stdlib + the ``git`` binary. It derives a
PEP 440-ish version from git:

- clean tag ``v1.2.3``           -> ``1.2.3``
- branch ahead of tag ``v1.2.3`` -> ``1.2.3+5.gabcdef``  (5 commits, at commit abcdef)
- no version tag yet             -> ``0.0.0+gabcdef``
- dirty working tree             -> appends ``.dirty`` to the local segment

and writes ``src/pydantic_ai_extensions/_version.py`` (gitignored) so the installed
package carries its exact build provenance, readable at runtime via
``pydantic_ai_extensions.__version__`` / ``__commit__``.

The package-metadata version in ``[project]`` stays a static release line (``0.1.0``);
``__version__`` is the authoritative *precise* identifier (tag + commit + dirty).
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path
from typing import Any

_PACKAGE = "pydantic_ai_extensions"
_VERSION_FILE = Path("src") / _PACKAGE / "_version.py"
_TAG_MATCH = "v[0-9]*"

# BuildHookInterface lives in hatchling, which is the build backend (always present at
# build time). The guard lets ``make version`` import this module's pure helpers from a
# dev venv where hatchling is not installed.
try:  # pragma: no cover - import-time environment branch
    from hatchling.builders.hooks.plugin.interface import BuildHookInterface
except ImportError:  # pragma: no cover
    BuildHookInterface = object  # type: ignore[assignment, misc]


def _git(root: Path, *args: str) -> str:
    try:
        result = subprocess.run(
            ["git", "-C", str(root), *args],
            capture_output=True,
            text=True,
            timeout=3,
            check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return ""
    return result.stdout.strip() if result.returncode == 0 else ""


def _normalize_version(describe: str, short_sha: str, dirty: bool) -> str:
    """Turn stripped ``git describe`` output into a PEP 440-ish version string.

    Mirrors ``version.py._normalize_version`` -- keep the two in sync.
    """
    m = re.match(r"^v?(\d[^-]*)-(\d+)-g([0-9a-f]+)$", describe)
    if m:
        base, local = m.group(1), f"{m.group(2)}.g{m.group(3)}"
    elif describe and re.fullmatch(r"[0-9a-f]{7,40}", describe):
        # `--always` fallback: bare abbreviated commit, no version tag reachable
        base, local = "0.0.0", f"g{describe}"
    else:
        tag = re.sub(r"^v", "", describe)
        if tag and re.match(r"^\d", tag):
            # a clean version tag, e.g. v1.2.3 -> 1.2.3
            base, local = tag, ""
        else:  # no git available at all
            base, local = "0.0.0", "unknown"
    if dirty:
        local = f"{local}.dirty" if local else "dirty"
    return f"{base}+{local}" if local else base


def _version_info_tuple(version: str) -> tuple[int | str, ...]:
    base = version.split("+", 1)[0]
    parts: list[int | str] = []
    for chunk in base.split("."):
        if chunk.isdigit():
            parts.append(int(chunk))
        elif chunk:
            parts.append(chunk)
    return tuple(parts)


def collect(root: Path) -> dict[str, str]:
    """Gather git provenance at ``root``.

    Git is only trusted when ``root`` is the top level of its own work tree: a
    ``.git``-less source tree (e.g. an unpacked tarball) nested inside an
    unrelated repository must not silently inherit that repo's tags and commits.
    """
    top = _git(root, "rev-parse", "--show-toplevel")
    if not top or Path(top).resolve() != root.resolve():
        describe_raw = short_sha = full_sha = branch = ""
    else:
        describe_raw = _git(root, "describe", "--tags", "--always", f"--match={_TAG_MATCH}", "--dirty")
        short_sha = _git(root, "rev-parse", "--short", "HEAD")
        full_sha = _git(root, "rev-parse", "HEAD")
        branch = _git(root, "rev-parse", "--abbrev-ref", "HEAD")
    dirty = bool(describe_raw) and describe_raw.endswith("-dirty")
    describe = describe_raw[: -len("-dirty")] if dirty else describe_raw
    return {
        "version": _normalize_version(describe, short_sha, dirty),
        "commit": short_sha,
        "commit_full": full_sha,
        "branch": branch or "(detached)",
        "describe": describe or "(unknown)",
        "dirty": "true" if dirty else "false",
    }


_TEMPLATE = '''\
"""Build provenance - generated by hatch_build.py, do not edit (gitignored)."""

from __future__ import annotations

__version__ = {version!r}
__version_info__ = {version_info!r}
__commit__ = {commit!r}
__commit_full__ = {commit_full!r}
__branch__ = {branch!r}
__describe__ = {describe!r}
__dirty__ = {dirty!r}
'''


def render_version_file(info: dict[str, str]) -> str:
    return _TEMPLATE.format(
        version=info["version"],
        version_info=_version_info_tuple(info["version"]),
        commit=info["commit"],
        commit_full=info["commit_full"],
        branch=info["branch"],
        describe=info["describe"],
        dirty=info["dirty"],
    )


def write_version_file(root: Path) -> dict[str, str]:
    info = collect(root)
    target = root / _VERSION_FILE
    if not info["commit"] and target.exists():
        # No git reachable (e.g. building a wheel *from* an sdist, which has no .git),
        # but a ``_version.py`` was already baked (during the sdist build, when git was
        # present). Preserve it instead of clobbering with ``0.0.0+unknown``.
        return info
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_version_file(info), encoding="utf-8")
    return info


class CustomBuildHook(BuildHookInterface):  # type: ignore[misc]
    """Registered via ``[tool.hatch.build.hooks.custom]`` in pyproject.toml."""

    PLUGIN_NAME = "git-version"

    def initialize(self, version: str, build_data: dict[str, Any]) -> None:
        write_version_file(Path(self.root))
        # The generated file is gitignored, so the sdist (VCS-filtered) would drop it.
        # Force it in so a wheel built *from* that sdist still carries provenance -- the
        # hook then preserves it (see ``write_version_file``) instead of rewriting unknown.
        if self.target_name == "sdist":
            build_data.setdefault("force_include", {})[str(Path(self.root) / _VERSION_FILE)] = str(_VERSION_FILE)
        self.app.display_debug(f"pydantic-ai-extensions: baked for {self.target_name}")
